### ISSUE TITLE
therealnews.com 

### ISSUE THREAD

**Issue by laurengarcia** [duckduckgo/content-blocking-whitelist#42]
Hey!

Not sure if you've split up the whitelists, but this rule triggers mixed content blocking on video pages, example: http://therealnews.com/t2/index.php?option=com_content&task=view&id=31&Itemid=74&jumival=21337

**Comment by dharb** [comment]
Thanks for the heads up @laurengarcia! I'll get that taken care of right away 🛩

**Comment by dharb** [comment]
Fixed!
